export { default as onca } from '@assets/characters/personagem-1-onca.png';
export { default as calango } from '@assets/characters/personagem-2-calango.png';
export { default as chacal } from '@assets/characters/personagem-3-chacal.png';
export { default as soin } from '@assets/characters/personagem-4-soin.png';
export { default as acucar } from '@assets/items/acucar.png';
export { default as carvao } from '@assets/items/carvao.png';
export { default as madeira } from '@assets/items/madeira.png';
export { default as niobio } from '@assets/items/niobio.png';
export { default as cafe } from '@assets/items/cafe.png';
export { default as machareta } from '@assets/items/machareta.png';
export { default as cerraca } from '@assets/items/cerraca.png';
export { default as bridge } from '@assets/items/ponte.png';
export { default as wall } from '@assets/items/muralha.png';
export { default as marquinho_icon } from '@assets/merchant_icons/m.png';
export { default as marquinho_background } from '@assets/backgrounds/background_coruja.png';
export { default as marquinho_image } from '@assets/merchant_images/Mercador 3 - Coruja_neutra.png';
export { default as marquinho_angryImage } from '@assets/merchant_images/Mercador 3 - Coruja_brava.png';
export { default as estranho_icon } from '@assets/merchant_icons/e.png';
export { default as estranho_background } from '@assets/backgrounds/background_mosca.png';
export { default as estranho_image } from '@assets/merchant_images/Mercador 1 - Mosca_direita.png';
export { default as estranho_image_2 } from '@assets/merchant_images/Mercador 1 - Mosca_esquerda.png';
export { default as chico_icon } from '@assets/merchant_icons/c.png';
export { default as chico_background } from '@assets/backgrounds/background_macaco.png';
export { default as chico_image } from '@assets/merchant_images/Mercador 2 - Macaco_neutro.png';